### PR TITLE
⚡️react@16.x, babel@7.x, jest > mocha, React.Fragment

### PR DESCRIPTION
**Pull request by JeromeFitz**
This removes the `peer dependency` warning with react@16.

This should not be a breaking change, despite the architectural changes. 

Upgrades all dependencies
* `react`
* `babel`
* etc.

Code Alterations
* `jest` over `mocha`, while still using `enzyme`
* * coverage, snapshots
* `babel` over prepublish script
* `prettier` and other `eslint` features

Also we now utilize `React.Fragment` instead of `span` if no `onSSR` Component is provided.

All of this to reduce the file size by a slim margin. But again, removes the warning, and keeps everything up-to-date (somewhat, as much as any repo can be). 😁

### CODE REVIEW

**Comment by JeromeFitz** [comment]
The `yarn.lock` is what makes this look like a big(ish) commit. (5,455 of 5,762 additions, ~95%)

Can be removed and a reworked `package.json` to reflect as well (and potentially ignore lock files altogether, your call). Or kept too. It doesn't really hurt anything. We may want to update the README to reflect.

Also if we'd rather have the majority of configuration in `package.json` as opposted to `.dotfiles` let me know.

**Comment by chuyik** [comment]
For anyone interested, I've forked this PR into a new package `@chuyik/react-no-ssr`.

npm: https://www.npmjs.com/package/@chuyik/react-no-ssr
github: https://github.com/chuyik/react-no-ssr

**Comment by JeromeFitz** [comment]
Latest update uses `useEffect` and `useState`.

**Comment by JeromeFitz** [comment]
Oh nice @chuyik! Great idea. 😎 

Yea, I wouldn't pull in my latest changes then since you are keeping support for React 15. 👍

**Pull request closed without merging**
